apiVersion: v1
kind: Namespace
metadata:
  name: helloworld
---
# service
apiVersion: v1
kind: Service
metadata:
  name: hello-service
  namespace: helloworld
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: helloworld
---
# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  namespace: helloworld
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - image: kavi106/launch-i-app:hellov1
        name: helloworld
        ports:
        - containerPort: 80